# This is a system-wide configuration file used to
# keep track of registries for various container backends.
# It adheres to TOML format and does not support recursive
# lists of registries.

# The default location for this configuration file is /etc/containers/registries.conf.

unqualified-search-registries = ['docker.io', 'quay.io', 'ghcr.io', 'registry.fedoraproject.org']

# Example registry rewrite rule:
# [[registry]]
# prefix="docker.io/library"
# location="127.0.0.1:60333/libpod"
# insecure=true
