name: Verify

on:
  # Trigger the workflow on push or pull request on master branch
  workflow_dispatch:

jobs:
  build:
    name: Build amd64
    runs-on: ubuntu-22.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Print environment
      run: |
        uname -a
        docker --version

    - name: Build & test linux/amd64 image
      run: make images test

    - name: Build amd64 binaries and tar archive
      run: make clean tar
