name: Verify

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: verify-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU (for emulation of other arches)
        uses: docker/setup-qemu-action@v2
        with:
          # Optional: beschränke auf die Plattformen, die du brauchst
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Print environment
        run: |
          uname -a
          docker --version
          docker buildx version

      - name: Build & test linux/amd64 image
        # Bewahre dein bestehendes Make-Setup; Buildx ist eingerichtet
        run: make images test
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Build multi-arch images and binaries
        run: make clean multiarch-tar
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
